server:
  port: 8100

spring:
  config:
    import:
      - app/cors/cors.yml
      - app/time/time.yml # classpath:/app/time/time.yml
      - app/jwt/jwt.yml

  jackson:
    serialization:
      write-dates-as-timestamps: false

  data:
    mongodb:
      username: root
      password: root
      database: board
      authentication-database: admin
      port: 27027
      host: localhost
    redis:
      host: localhost
      port: 6379

  elasticsearch:
    uris: http://localhost:9200