server:
  port: 8100

spring:
  config:
    import:
      - app/cors/cors.yml
      - app/time/time.yml # classpath:/app/time/time.yml
      - app/jwt/jwt.yml

  data:
    mongodb:
      username: root
      password: root
      database: board
      authentication-database: admin
      port: 27027
      host: 3.35.139.172
    redis:
      host: 3.35.139.172
      port: 6379
