server:
  port: 8100

spring:
  config:
    import:
      - optional:file:.env[.properties]
      - app/cors/cors-local.yml
      - app/time/time.yml # classpath:/app/time/time.yml
      - app/jwt/jwt.yml
      - app/aws/aws-local.yml

  jackson:
    serialization:
      write-dates-as-timestamps: false

  data:
    mongodb:
      username: root
      password: root
      database: board
      authentication-database: admin
      port: 27027
      host: localhost
    redis:
      host: localhost
      port: 6379

  elasticsearch:
    uris: http://localhost:9200

#cloud:
#  aws:
#    s3:
#      bucket: ${bucket}
#    credentials:
#      access-key: ${accessKey}
#      secret-key: ${secretKey}
#    region:
#      static: ${region}
#      auto: false
#    stack:
#      auto: false