server:
  port: 9090

spring:
  config:
    import:
      - app/cors/cors-local.yml
      - app/jwt/jwt.yml
      - app/time/time.yml # classpath:/app/time/time.yml

  datasource:
    url: jdbc:postgresql://localhost:5442/profile
    username: ${POSTGRES_USER:root}
    password: ${POSTGRES_PASSWORD:root}
    driver-class-name: org.postgresql.Driver

    hikari:
      connection-timeout: 10000
      idle-timeout: 10000
      validation-timeout: 10000
      max-lifetime: 580000

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false

  data:
    mongodb:
      host: localhost
      port: 27017
      username: root
      password: root
      database: profile-log
      authentication-database: admin

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:/db/migration # 기본값

