server:
  port: 8090

spring:
  config:
    import:
      - app/cors/cors.yml
      - app/jwt/jwt.yml
      - app/time/time.yml # classpath:/app/time/time.yml

  datasource:
    url: ${PROFILE_URL:jdbc:postgresql://rdb-blog-member-profile.cl002464cek4.ap-northeast-2.rds.amazonaws.com:5442/profile}
    username: ${POSTGRES_USER:blog_admin}
    password: ${POSTGRES_PASSWORD:rhehdgur23!}
    driver-class-name: org.postgresql.Driver

    hikari:
      connection-timeout: 10000
      idle-timeout: 10000
      validation-timeout: 10000
      max-lifetime: 580000

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false

  data:
    mongodb:
      host: 3.35.139.172
      port: 27017
      username: root
      password: root
      database: profile-log
      authentication-database: admin

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:/db/migration # 기본값

