server:
  port: 8080

spring:
  config:
    import:
      - app/cors/cors.yml
      - app/time/time.yml # classpath:/app/time/time.yml
      - app/jwt/jwt.yml
      - app/password/password-encoder.yml

  datasource:
    url: ${MEMBER_URL:jdbc:postgresql://localhost:5432/member}
    username: ${POSTGRES_USER:root}
    password: ${POSTGRES_PASSWORD:root}
    driver-class-name: org.postgresql.Driver

    hikari:
      connection-timeout: 10000
      idle-timeout: 10000
      validation-timeout: 10000
      max-lifetime: 580000

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:/db/migration # 기본값

  data:
    redis:
      host: localhost
      port: 6379
