server:
  port: 9000

spring:
  config:
    import:
      - optional:file:.env[.properties]
      - app/cors/cors.yml
      - app/time/time.yml # classpath:/app/time/time.yml

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:yoehadu815}
    password: ${MAIL_PASSWORD:ouairpfouushtwwm}
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true